name: dl_project
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1
  - blas=1.0
  - bottleneck=1.3.7
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - eigen=3.4.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - ffmpeg=4.2.3
  - freetype=2.10.4
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - hdf5=1.12.1
  - icc_rt=2022.1.0
  - icu=58.2
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - intel-openmp=2024.0.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jpeg=9e
  - jupyter_client=8.6.1
  - jupyter_core=5.5.0
  - lerc=3.0
  - libclang=12.0.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libglib=2.78.4
  - libiconv=1.17
  - libogg=1.3.4
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - opencv=4.6.0
  - openjpeg=2.4.0
  - openssl=3.0.13
  - packaging=24.0
  - pandas=2.1.1
  - parso=0.8.4
  - pcre2=10.42
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.12.2
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - pywin32=305
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - attrs==23.2.0
    - blosc2==2.6.0
    - certifi==2024.2.2
    - charset-normalizer==3.3.2
    - clip==1.0
    - contourpy==1.2.0
    - cox==0.1.post3
    - cycler==0.12.1
    - datasets==2.19.0
    - dill==0.3.8
    - filelock==3.13.3
    - fonttools==4.50.0
    - frozenlist==1.4.1
    - fsspec==2024.3.1
    - ftfy==6.2.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - gputil==1.4.0
    - grpcio==1.62.1
    - huggingface-hub==0.22.2
    - idna==3.6
    - jinja2==3.1.3
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - markupsafe==2.1.5
    - matplotlib==3.8.3
    - mpmath==1.3.0
    - msgpack==1.0.8
    - multidict==6.0.5
    - multiprocess==0.70.16
    - ndindex==1.8
    - networkx==3.2.1
    - opencv-python==4.9.0.80
    - pillow==10.3.0
    - protobuf==5.26.1
    - psutil==5.9.8
    - py-cpuinfo==9.0.0
    - py3nvml==0.2.7
    - pyarrow==16.0.0
    - pyarrow-hotfix==0.6
    - pyparsing==3.1.2
    - pyyaml==6.0.1
    - regex==2023.12.25
    - requests==2.31.0
    - robustness==1.2.1.post2
    - safetensors==0.4.2
    - scikit-learn==1.4.1.post1
    - scipy==1.12.0
    - seaborn==0.13.2
    - smmap==5.0.1
    - sympy==1.12
    - tables==3.9.2
    - tensorboardx==2.6.2.2
    - threadpoolctl==3.4.0
    - timm==0.9.16
    - torch==2.2.2
    - torchvision==0.17.2
    - tqdm==4.66.2
    - typing-extensions==4.10.0
    - urllib3==2.2.1
    - xmltodict==0.13.0
    - xxhash==3.4.1
    - yarl==1.9.4
